# Generated by Django 4.2 on 2024-10-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('institucion_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('institucion_direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('institucion_nit', models.CharField(max_length=20, verbose_name='Nit')),
                ('institucion_contactos', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('institucion_telefono', models.CharField(max_length=50, unique=True, verbose_name='Telefono')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
