FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Instalar wget y descargar wait-for-it.sh
RUN apt-get update && apt-get install -y wget
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

COPY . .

EXPOSE 8003

# Esperar a que PostgreSQL esté listo antes de ejecutar runserver
CMD ["wait-for-it.sh", "db_gateway:5432", "--", "python", "gateway_service/manage.py", "runserver", "0.0.0.0:8003"]
